/**
 * Gemini AI provider adapter — wraps Google Gemini 3.1 Flash Image API.
 * Extracted from server.ts inline logic into the AIProvider interface.
 */

import { GoogleGenAI } from '@google/genai';
import type { AIProvider, ImageInput, AIResult, SharpenAnalysis } from './types.js';
import { parseSharpenAnalysis, SHARPEN_ANALYSIS_PROMPT } from './sharpen-prompt.js';

export class GeminiProvider implements AIProvider {
  readonly name = 'gemini' as const;
  readonly displayName = 'Google Gemini';

  private ai: GoogleGenAI;

  constructor(apiKey: string) {
    this.ai = new GoogleGenAI({ apiKey });
  }

  async generatePackshot(images: ImageInput[]): Promise<AIResult> {
    const response = await this.ai.models.generateContent({
      model: 'gemini-3.1-flash-image-preview',
      contents: {
        parts: [
          {
            text: 'Generate a professional, commercial-grade packshot of the product shown in these images. Follow the system instructions strictly: PURE WHITE background, ZERO creativity, EXACT product fidelity. Create ONE high-quality "Hero Shot" that represents the product perfectly.',
          },
          ...images.map(img => ({
            inlineData: { data: img.base64, mimeType: img.mimeType },
          })),
        ],
      },
      config: {
        systemInstruction:
          'YOU ARE A TECHNICAL PRODUCT PHOTOGRAPHY SYNTHESIS ENGINE. STRICT REQUIREMENTS: 1. BACKGROUND: ABSOLUTE PURE WHITE (#FFFFFF). 2. FIDELITY: IDENTICAL REPLICA OF SOURCE. 3. CREATIVITY: ZERO. 4. LIGHTING: EVEN STUDIO. 5. COMPOSITION: CENTERED, SHARP FOCUS.',
        imageConfig: { aspectRatio: '1:1', imageSize: '1K' },
      },
    });

    return this.extractImage(response);
  }

  async homogenize(
    currentImage: string,
    sourceImages: ImageInput[],
    burnt: number,
    dark: number
  ): Promise<AIResult> {
    const currentBase64 = currentImage.replace(/^data:image\/\w+;base64,/, '');
    const response = await this.ai.models.generateContent({
      model: 'gemini-3.1-flash-image-preview',
      contents: {
        parts: [
          {
            text: `Apply lighting homogenization: reduce overexposed highlights by ${burnt}%, lift underexposed shadows by ${dark}%. Maintain product fidelity and pure white background.`,
          },
          { inlineData: { data: currentBase64, mimeType: 'image/png' } },
          ...sourceImages.map(img => ({
            inlineData: { data: img.base64, mimeType: img.mimeType },
          })),
        ],
      },
      config: {
        systemInstruction:
          'YOU ARE A TECHNICAL PRODUCT PHOTOGRAPHY LIGHTING SPECIALIST. Normalize lighting. Maintain product fidelity. Keep background pure white.',
        imageConfig: { aspectRatio: '1:1', imageSize: '1K' },
      },
    });

    return this.extractImage(response);
  }

  async editImage(
    currentImage: string,
    sourceImages: ImageInput[],
    prompt: string
  ): Promise<AIResult> {
    const currentBase64 = currentImage.replace(/^data:image\/\w+;base64,/, '');
    const response = await this.ai.models.generateContent({
      model: 'gemini-3.1-flash-image-preview',
      contents: {
        parts: [
          {
            text: `Apply this specific modification: "${prompt}". Only change what's requested. Maintain product fidelity and pure white background.`,
          },
          { inlineData: { data: currentBase64, mimeType: 'image/png' } },
          ...(sourceImages || []).map(img => ({
            inlineData: { data: img.base64, mimeType: img.mimeType },
          })),
        ],
      },
      config: {
        systemInstruction:
          'YOU ARE A TECHNICAL PRODUCT PHOTOGRAPHY EDITOR. Apply ONLY the requested change. Maintain fidelity for everything else. Keep background pure white.',
        imageConfig: { aspectRatio: '1:1', imageSize: '1K' },
      },
    });

    return this.extractImage(response);
  }

  async analyzeForSharpening(image: ImageInput): Promise<SharpenAnalysis> {
    const response = await this.ai.models.generateContent({
      model: 'gemini-2.0-flash',   // text-only response — no image generation needed
      contents: {
        parts: [
          { text: SHARPEN_ANALYSIS_PROMPT },
          { inlineData: { data: image.base64, mimeType: image.mimeType } },
        ],
      },
      config: { responseMimeType: 'application/json' },
    });

    const text = response.candidates?.[0]?.content?.parts?.[0]?.text ?? '';
    return parseSharpenAnalysis(text);
  }

  /** Extract base64 image from Gemini response. */
  private extractImage(response: any): AIResult {
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return { image: `data:image/png;base64,${part.inlineData.data}` };
      }
    }
    throw new Error('No image generated by Gemini');
  }
}
