/**
 * Grok (xAI) AI provider adapter — uses xAI API which is OpenAI-compatible.
 * Uses grok-2-vision for multimodal analysis and aurora for image generation.
 */

import OpenAI from 'openai';
import type { AIProvider, ImageInput, AIResult, SharpenAnalysis } from './types.js';
import { parseSharpenAnalysis, SHARPEN_ANALYSIS_PROMPT } from './sharpen-prompt.js';

export class GrokProvider implements AIProvider {
  readonly name = 'grok' as const;
  readonly displayName = 'xAI Grok';

  private client: OpenAI;

  constructor(apiKey: string) {
    // xAI uses OpenAI-compatible API at a different base URL
    this.client = new OpenAI({
      apiKey,
      baseURL: 'https://api.x.ai/v1',
    });
  }

  async generatePackshot(images: ImageInput[]): Promise<AIResult> {
    const imageMessages = images.map(img => ({
      type: 'image_url' as const,
      image_url: { url: `data:${img.mimeType};base64,${img.base64}` },
    }));

    // Use Grok vision model to analyze product
    const analysisResponse = await this.client.chat.completions.create({
      model: 'grok-2-vision-latest',
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: 'Describe this product in detail for a professional packshot photo generation. Include: shape, colors, textures, materials, branding, dimensions. Be precise and technical.',
            },
            ...imageMessages,
          ],
        },
      ],
      max_tokens: 500,
    });

    const description = analysisResponse.choices[0]?.message?.content || '';

    // Use Aurora image generation model
    const imageResponse = await this.client.images.generate({
      model: 'aurora',
      prompt: `Professional product packshot photograph on pure white background (#FFFFFF). Even studio lighting, centered composition, sharp focus. Product: ${description.slice(0, 500)}`,
      n: 1,
      size: '1024x1024',
      response_format: 'b64_json',
    });

    const b64 = imageResponse.data[0]?.b64_json;
    if (!b64) throw new Error('No image generated by Grok');

    return { image: `data:image/png;base64,${b64}` };
  }

  async homogenize(
    currentImage: string,
    sourceImages: ImageInput[],
    burnt: number,
    dark: number
  ): Promise<AIResult> {
    const currentBase64 = currentImage.replace(/^data:image\/\w+;base64,/, '');

    // Use Grok vision to analyze and describe needed corrections
    const analysisResponse = await this.client.chat.completions.create({
      model: 'grok-2-vision-latest',
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: `Analyze this product photo's lighting issues. Describe exactly what needs to change to reduce overexposed highlights by ${burnt}% and lift underexposed shadows by ${dark}%. Be specific about areas and corrections needed.`,
            },
            {
              type: 'image_url',
              image_url: { url: `data:image/png;base64,${currentBase64}` },
            },
          ],
        },
      ],
      max_tokens: 300,
    });

    const analysis = analysisResponse.choices[0]?.message?.content || '';

    // Generate corrected image with Aurora
    const imageResponse = await this.client.images.generate({
      model: 'aurora',
      prompt: `Product photo with corrected lighting: ${analysis.slice(0, 400)}. Pure white background, product fidelity maintained.`,
      n: 1,
      size: '1024x1024',
      response_format: 'b64_json',
    });

    const b64 = imageResponse.data[0]?.b64_json;
    if (!b64) throw new Error('No image generated by Grok');

    return { image: `data:image/png;base64,${b64}` };
  }

  async analyzeForSharpening(image: ImageInput): Promise<SharpenAnalysis> {
    // Grok uses OpenAI-compatible vision API
    const response = await this.client.chat.completions.create({
      model: 'grok-2-vision-latest',
      messages: [
        {
          role: 'user',
          content: [
            { type: 'text', text: SHARPEN_ANALYSIS_PROMPT },
            { type: 'image_url', image_url: { url: `data:${image.mimeType};base64,${image.base64}` } },
          ],
        },
      ],
      max_tokens: 600,
    });

    const text = response.choices[0]?.message?.content ?? '';
    return parseSharpenAnalysis(text);
  }

  async editImage(
    currentImage: string,
    _sourceImages: ImageInput[],
    prompt: string
  ): Promise<AIResult> {
    const currentBase64 = currentImage.replace(/^data:image\/\w+;base64,/, '');

    // Use Grok vision to understand current image + edit request
    const analysisResponse = await this.client.chat.completions.create({
      model: 'grok-2-vision-latest',
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: `Describe this product photo in detail, then explain exactly how to apply this edit: "${prompt}". Be specific about what changes and what stays the same.`,
            },
            {
              type: 'image_url',
              image_url: { url: `data:image/png;base64,${currentBase64}` },
            },
          ],
        },
      ],
      max_tokens: 400,
    });

    const analysis = analysisResponse.choices[0]?.message?.content || '';

    // Generate edited image
    const imageResponse = await this.client.images.generate({
      model: 'aurora',
      prompt: `Product packshot photo edit: ${analysis.slice(0, 400)}. Pure white background, maintain all unedited details.`,
      n: 1,
      size: '1024x1024',
      response_format: 'b64_json',
    });

    const b64 = imageResponse.data[0]?.b64_json;
    if (!b64) throw new Error('No image generated by Grok');

    return { image: `data:image/png;base64,${b64}` };
  }
}
