/**
 * OpenAI AI provider adapter — uses GPT-4o vision for analysis + GPT Image 1 for generation.
 * Uses chat completions API for vision analysis (stable types), images API for generation.
 */

import OpenAI, { toFile } from 'openai';
import type { AIProvider, ImageInput, AIResult, SharpenAnalysis } from './types.js';
import { parseSharpenAnalysis, SHARPEN_ANALYSIS_PROMPT } from './sharpen-prompt.js';

export class OpenAIProvider implements AIProvider {
  readonly name = 'openai' as const;
  readonly displayName = 'OpenAI';

  private client: OpenAI;

  constructor(apiKey: string) {
    this.client = new OpenAI({ apiKey });
  }

  async generatePackshot(images: ImageInput[]): Promise<AIResult> {
    // Step 1: Use GPT-4o vision to analyze the product from reference images
    const imageContent: OpenAI.Chat.Completions.ChatCompletionContentPart[] = images.map(img => ({
      type: 'image_url' as const,
      image_url: { url: `data:${img.mimeType};base64,${img.base64}` },
    }));

    const analysisResponse = await this.client.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: 'Describe this product in precise detail for generating a professional packshot photo. Include: exact shape, colors, textures, materials, branding elements, proportions. Be technical and specific.',
            },
            ...imageContent,
          ],
        },
      ],
      max_tokens: 500,
    });

    const description = analysisResponse.choices[0]?.message?.content || '';

    // Step 2: Generate packshot with GPT Image 1
    const imageResponse = await this.client.images.generate({
      model: 'gpt-image-1',
      prompt: `Professional product packshot photograph. Pure white background (#FFFFFF). Even studio lighting. Centered composition. Sharp focus. Product details: ${description.slice(0, 500)}`,
      n: 1,
      size: '1024x1024',
      quality: 'high',
    });

    const b64 = imageResponse.data[0]?.b64_json;
    if (!b64) throw new Error('No image generated by OpenAI');

    return { image: `data:image/png;base64,${b64}` };
  }

  async homogenize(
    currentImage: string,
    _sourceImages: ImageInput[],
    burnt: number,
    dark: number
  ): Promise<AIResult> {
    const currentBase64 = currentImage.replace(/^data:image\/\w+;base64,/, '');

    // Step 1: Analyze lighting with GPT-4o vision
    const analysisResponse = await this.client.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: `Analyze this product photo's lighting. Describe what needs to change to: reduce overexposed highlights by ${burnt}%, lift underexposed shadows by ${dark}%. Keep the pure white background and product fidelity. Be specific about areas.`,
            },
            {
              type: 'image_url',
              image_url: { url: `data:image/png;base64,${currentBase64}` },
            },
          ],
        },
      ],
      max_tokens: 300,
    });

    const analysis = analysisResponse.choices[0]?.message?.content || '';

    // Step 2: Edit image with lighting corrections
    const imageFile = await toFile(Buffer.from(currentBase64, 'base64'), 'image.png', { type: 'image/png' });
    const imageResponse = await this.client.images.edit({
      model: 'gpt-image-1',
      image: imageFile,
      prompt: `Apply lighting correction: ${analysis.slice(0, 300)}. Reduce highlights by ${burnt}%, lift shadows by ${dark}%. Maintain product fidelity and pure white background.`,
      size: '1024x1024',
    });

    const b64 = imageResponse.data[0]?.b64_json;
    if (!b64) throw new Error('No image generated by OpenAI');

    return { image: `data:image/png;base64,${b64}` };
  }

  async analyzeForSharpening(image: ImageInput): Promise<SharpenAnalysis> {
    const response = await this.client.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: [
            { type: 'text', text: SHARPEN_ANALYSIS_PROMPT },
            { type: 'image_url', image_url: { url: `data:${image.mimeType};base64,${image.base64}` } },
          ],
        },
      ],
      response_format: { type: 'json_object' },
      max_tokens: 600,
    });

    const text = response.choices[0]?.message?.content ?? '';
    return parseSharpenAnalysis(text);
  }

  async editImage(
    currentImage: string,
    _sourceImages: ImageInput[],
    prompt: string
  ): Promise<AIResult> {
    const currentBase64 = currentImage.replace(/^data:image\/\w+;base64,/, '');

    const imageFile = await toFile(Buffer.from(currentBase64, 'base64'), 'image.png', { type: 'image/png' });
    const imageResponse = await this.client.images.edit({
      model: 'gpt-image-1',
      image: imageFile,
      prompt: `Apply this modification to the product photo: "${prompt}". Only change what's requested. Maintain product fidelity and pure white background.`,
      size: '1024x1024',
    });

    const b64 = imageResponse.data[0]?.b64_json;
    if (!b64) throw new Error('No image generated by OpenAI');

    return { image: `data:image/png;base64,${b64}` };
  }
}
